

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NHPhuc_QuanLyBanHang.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class QuanLyBanHangEntities1 : DbContext
{
    public QuanLyBanHangEntities1()
        : base("name=QuanLyBanHangEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Donhang> Donhang { get; set; }

    public virtual DbSet<Donhangchitiet> Donhangchitiet { get; set; }

    public virtual DbSet<Hanghoa> Hanghoa { get; set; }

    public virtual DbSet<Loaihang> Loaihang { get; set; }

    public virtual DbSet<QTV> QTV { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

