
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NHPhuc_QuanLyBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int UserID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

    public string hoten { get; set; }

    public string gioitinh { get; set; }

    public string diachi { get; set; }



    public virtual QTV QTV { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }

}

}
